/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package advent.of.code



class App {

    val day1 : Day1 = Day1()

}

fun main(args: Array<String>) {
    println(App().day1.b())
}
